/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.motorph.usermanagement.view;

import com.motorph.usermanagement.controller.SystemController;
import java.util.logging.Logger;
import java.util.logging.Level;

/**
 *
 * @author harvey punsalan
 */
public class SystemAdminPage extends javax.swing.JFrame {
    private static final Logger logger = Logger.getLogger(SystemAdminPage.class.getName());
    private SystemController systemController;

    /**
     * Creates new form SystemAdminPage
     */
    public SystemAdminPage() {
        initComponents();
        initializeController();
    }
    
    /**
     * Initialize the system controller after components are created
     */
    private void initializeController() {
        try {
            systemController = new SystemController(this, jPanelContent);
            logger.info("SystemController initialized successfully");
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error initializing SystemController", e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelsideBar = new javax.swing.JPanel();
        jButtonPermission = new javax.swing.JButton();
        jButtonRole = new javax.swing.JButton();
        jButtonUser = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jPanelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1152, 648));

        jPanelsideBar.setBackground(new java.awt.Color(0, 102, 153));

        jButtonPermission.setBackground(new java.awt.Color(0, 102, 153));
        jButtonPermission.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButtonPermission.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPermission.setText("Permission");
        jButtonPermission.setBorder(null);

        jButtonRole.setBackground(new java.awt.Color(0, 102, 153));
        jButtonRole.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButtonRole.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRole.setText("Role");
        jButtonRole.setBorder(null);

        jButtonUser.setBackground(new java.awt.Color(0, 102, 153));
        jButtonUser.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButtonUser.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUser.setText("User");
        jButtonUser.setBorder(null);

        jButtonLogout.setBackground(new java.awt.Color(0, 102, 153));
        jButtonLogout.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        jButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogout.setText("Logout");
        jButtonLogout.setBorder(null);

        javax.swing.GroupLayout jPanelsideBarLayout = new javax.swing.GroupLayout(jPanelsideBar);
        jPanelsideBar.setLayout(jPanelsideBarLayout);
        jPanelsideBarLayout.setHorizontalGroup(
            jPanelsideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelsideBarLayout.createSequentialGroup()
                .addGroup(jPanelsideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelsideBarLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanelsideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonLogout)
                            .addComponent(jButtonUser)
                            .addComponent(jButtonRole)))
                    .addGroup(jPanelsideBarLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jButtonPermission)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanelsideBarLayout.setVerticalGroup(
            jPanelsideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelsideBarLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jButtonPermission)
                .addGap(18, 18, 18)
                .addComponent(jButtonRole)
                .addGap(26, 26, 26)
                .addComponent(jButtonUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 348, Short.MAX_VALUE)
                .addComponent(jButtonLogout)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1006, Short.MAX_VALUE)
        );
        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelsideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelsideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1303, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Getter methods for controller access to buttons
     * 
     * @return the Permission JButton
     */
    public javax.swing.JButton getPermissionButton() {
        return jButtonPermission;
    }
    
    public javax.swing.JButton getRoleButton() {
        return jButtonRole;
    }
    
    public javax.swing.JButton getUserButton() {
        return jButtonUser;
    }
    
    public javax.swing.JButton getLogoutButton() {
        return jButtonLogout;
    }
    
    public javax.swing.JPanel getContentPanel() {
        return jPanelContent;
    }
    
    public SystemController getSystemController() {
        return systemController;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SystemAdminPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonPermission;
    private javax.swing.JButton jButtonRole;
    private javax.swing.JButton jButtonUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelsideBar;
    // End of variables declaration//GEN-END:variables
}
